#!/bin/bash

#timeout=$(xset q | grep timeout | cut -d ' ' -f 5) * 1000
#timeout=1200000
lockMin=1
suspendMin=20
lockTimeout=$(( $lockMin * 60000 ))
suspendTimeout=$(( $suspendMin * 60000 ))
#timeout=300000


while true
do
    audio=$(pacmd list-sinks | grep -A 4 "*" | grep "state: " | cut -c 9-)
    clock=$(date +%H%M)
    time=$(xprintidle)
    echo $time
    echo $audio

    if [[ $time -gt $lockTimeout && $audio != "RUNNING" ]];
    then
        multilockscreen -l
        sleep 10
    fi
    if [[ $time -gt $suspendTimeout && ("$clock" < "04:45" || "$clock" > "06:15" ) ]];
    #echo "Checking time.."
    then
        #echo $time is gt $timeout and $clock is lt 0915 or $clock is gt 0950
        #echo "Suspend"
        sudo systemctl suspend
        sleep 10
    #else
        #echo $time is lt $timeout or $clock is gt 0915 and $clock is lt 0950
        #echo "stay awake"
    fi
    #echo "sleeping.."
    sleep 60
done
