#!/bin/bash


#in ms
timeout=300000


while true
do
    clock=$(date +%H%M)
    time=$(xprintidle)
    #echo $time
    if [[ $time -gt $timeout && ("$clock" < "04:45" || "$clock" > "06:15" ) ]];
    #echo "Checking time.."
    #if [[ $time -gt $timeout && ("$clock" < "14:15" || "$clock" > "15:30" ) ]];
    then
        #echo $time is gt $timeout and $clock is lt 0915 or $clock is gt 0950
        #echo "Suspend"
        sudo systemctl suspend
        sleep 10
    #else
        #echo $time is lt $timeout or $clock is gt 0915 and $clock is lt 0950
        #echo "stay awake"
    fi
    #echo "sleeping.."
    sleep 60
done
